apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: todo-app
          image: "{{ .Values.todoApp.image.repository }}:{{ .Values.todoApp.image.tag }}"
          imagePullPolicy: {{ .Values.todoApp.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.todoApp.service.targetPort }}
              protocol: TCP
          env:
            {{- range .Values.todoApp.env }}
            - name: {{ .name }}
              {{- if .value }}
              value: {{ .value | quote }}
              {{- else if .valueFrom }}
              valueFrom:
                {{- toYaml .valueFrom | nindent 16 }}
              {{- end }}
            {{- end }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.todoApp.database.existingSecret }}
                  key: password
          resources:
            {{- toYaml .Values.todoApp.resources | nindent 12 }}
