apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.todoApp.database.existingSecret }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.credentials.username | b64enc }}
  password: {{ .Values.credentials.password | b64enc }}
