namespace: keycloak

# Whether this chart should create the namespace
createNamespace: false

# Database configuration
database:
  type: cnpg  # Options: cnpg, postgres
  cnpg:
    enabled: true
  postgres:
    enabled: false

secrets:
  postgres:
    name: postgres-credentials
    admin:
      name: nkwenti
      password: password
  tls:
    name: tls-secret
    cert: ""
    key: ""
  keycloak:
    name: keycloak-secrets
    # Set to true only on first install; then set to false to avoid duplicate admin creation
    bootstrap: false
    admin:
      name: nkwenti
      password: password

deployments:
  securePort: 80
  postgres:
    image:
      name: 192.168.56.10:5000/cloudnative-pg/postgresql:14
    db:
      name: keycloak
    service:
      name: postgres
      port: 5432
    volume:
      name: postgres-storage
      path: /var/lib/postgresql/data
  keycloak:
    service:
      name: keycloak
    ports:
      containerPort: 9000
    image: "192.168.56.10:5000/keycloak/keycloak:26.3.3"
  ingress:
    host: keycloak.local

pv:
  name: postgres-pv
  size: 512Mi
pvc:
  name: postgres-pvc
  size: 512Mi
