apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.keycloak.image.repository }}:{{ .Values.keycloak.image.tag }}"
          imagePullPolicy: {{ .Values.keycloak.image.pullPolicy }}
          command: ["/opt/keycloak/bin/kc.sh"]
          args: ["start-dev"]
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: https
              containerPort: 8443
              protocol: TCP
          env:
            - name: KEYCLOAK_ADMIN
              value: {{ .Values.keycloak.auth.adminUser | quote }}
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-admin-credentials
                  key: password
            - name: KC_DB
              value: {{ .Values.keycloak.db.vendor | quote }}
            - name: KC_DB_URL
              value: "jdbc:postgresql://{{ .Values.keycloak.db.host }}:{{ .Values.keycloak.db.port }}/{{ .Values.keycloak.db.name }}"
            - name: KC_DB_USERNAME
              value: {{ .Values.keycloak.db.username | quote }}
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.keycloak.db.existingSecret }}
                  key: password
            - name: KC_HOSTNAME
              value: {{ .Values.keycloak.ingress.hostname | quote }}
          resources:
            {{- toYaml .Values.keycloak.resources | nindent 12 }}
