apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.deployments.keycloak.service.name }}"
  namespace: "{{ .Values.namespace }}"
  labels:
    app: "{{ .Values.deployments.keycloak.service.name }}"
spec:
  ports:
    - name: http
      port: {{ .Values.deployments.securePort }}
      targetPort: {{ .Values.deployments.keycloak.ports.containerPort }}
  selector:
    app: "{{ .Values.deployments.keycloak.service.name }}"
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.deployments.keycloak.service.name }}"
  namespace: "{{ .Values.namespace }}"
  labels:
    app: "{{ .Values.deployments.keycloak.service.name }}"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: "{{ .Values.deployments.keycloak.service.name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.deployments.keycloak.service.name }}"
    spec:
      containers:
        - name: "{{ .Values.deployments.keycloak.service.name }}"
          image: {{ .Values.deployments.keycloak.image | default "localhost:5000/quay.io/keycloak/keycloak:26.3.3" }}
          args: ["start-dev"]
          env:
            {{- if .Values.secrets.keycloak.bootstrap }}
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  key: KEYCLOAK_ADMIN
                  name: "{{ .Values.secrets.keycloak.name }}"
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: KEYCLOAK_ADMIN_PASSWORD
                  name: "{{ .Values.secrets.keycloak.name }}"
            {{- end }}
            - name: KC_PROXY
              value: "edge"
            - name: KC_HEALTH_ENABLED
              value: "true"
            - name: KC_METRICS_ENABLED
              value: "true"
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "false"
            - name: KC_LOG_LEVEL
              value: INFO
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL
              value: "jdbc:postgresql://{{ .Values.deployments.postgres.service.name }}-rw.{{ .Values.namespace }}.svc/{{ .Values.deployments.postgres.db.name }}"
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.secrets.postgres.name }}"
                  key: POSTGRES_USER
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.secrets.postgres.name }}"
                  key: POSTGRES_PASSWORD
          ports:
            - name: http
              containerPort: {{ .Values.deployments.keycloak.ports.containerPort }}
          # Probes disabled for manual verification per request
          resources:
            limits:
              memory: 1536Mi
              cpu: "1"
            requests:
              memory: 1024Mi
              cpu: "0.5"
