{{- if .Values.keycloak.extraConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.keycloak.extraConfig }}
  {{ $key }}: |-
    {{- $value | nindent 4 }}
{{- end }}
{{- end }}
