apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "keycloak.name" . }}
    helm.sh/chart: {{ include "keycloak.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.keycloak.db.username | default "postgres" | quote }}
  password: {{ .Values.keycloak.db.password | default "aab++112" | quote }}
