apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-admin-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  username: {{ .Values.keycloak.auth.adminUser | b64enc | quote }}
  password: {{ .Values.keycloak.auth.adminPassword | b64enc | quote }}
  management-username: {{ .Values.keycloak.auth.managementUser | b64enc | quote }}
  management-password: {{ .Values.keycloak.auth.managementPassword | b64enc | quote }}
