apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.postgresql.name }}-pv
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: {{ .Values.postgresql.storage.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/{{ .Values.postgresql.name }}"