apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresql.name }}
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    cnpg.io/cluster: {{ .Values.postgresql.name }}