apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-data-pvc
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi # Adjust size as needed for Gitea application data
  storageClassName: hostpath-provisioner