apiVersion: v1
kind: Service
metadata:
  name: gitea
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: 3000
      targetPort: http
    - name: ssh
      port: 22
      targetPort: ssh
  selector:
    app.kubernetes.io/name: gitea