{{- if .Values.postgresql.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Release.Name }}-db
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
spec:
  instances: 1
  imageName: 192.168.56.10:5000/cloudnative-pg/postgresql:14
  enableSuperuserAccess: true
  
  bootstrap:
    initdb:
      database: {{ .Values.gitea.database.name }}
      owner: {{ .Values.gitea.database.user }}
      secret:
        name: {{ .Values.gitea.database.existingSecret }}
  
  storage:
    size: 512Mi
    storageClass: {{ .Values.postgresql.storageClass | quote }}
    
  walStorage:
    size: 512Mi
    storageClass: {{ .Values.postgresql.storageClass | quote }}
  
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
{{- end }}
