{{- if .Values.gitea.persistence.enabled }}
{{- $pvcName := printf "%s-data" .Release.Name }}
{{- $existingPvc := lookup "v1" "PersistentVolumeClaim" .Release.Namespace $pvcName }}
{{- if not $existingPvc }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-data
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.gitea.persistence.storageClass }}
  {{- if (eq "-" .Values.gitea.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.gitea.persistence.storageClass | quote }}
  {{- end }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.gitea.persistence.size }}
{{- end }}
{{- end }}
