{{- if .Values.operator.installCRDs }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusters.postgresql.cnpg.io
  labels:
    app.kubernetes.io/name: {{ .Values.operator.fullnameOverride }}
    app.kubernetes.io/component: operator
spec:
  group: postgresql.cnpg.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              instances:
                type: integer
                minimum: 1
              imageName:
                type: string
              storage:
                type: object
                properties:
                  size:
                    type: string
                  storageClass:
                    type: string
              superuserSecret:
                type: object
                properties:
                  name:
                    type: string
              bootstrap:
                type: object
                properties:
                  initdb:
                    type: object
                    properties:
                      database:
                        type: string
                      owner:
                        type: string
                      dataChecksums:
                        type: boolean
              monitoring:
                type: object
                properties:
                  enablePodMonitor:
                    type: boolean
                  podMonitor:
                    type: object
                    properties:
                      labels:
                        type: object
  scope: Namespaced
  names:
    plural: clusters
    singular: cluster
    kind: Cluster
    shortNames:
    - pg
    - pgsql
    - postgresql
{{- end }}
