apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.operator.fullnameOverride }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.operator.fullnameOverride }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.operator.fullnameOverride }}
    spec:
      serviceAccountName: {{ .Values.operator.fullnameOverride }}
      containers:
        - name: operator
          image: "{{ .Values.operator.image.name }}:{{ .Values.operator.image.tag }}"
          imagePullPolicy: IfNotPresent
          args:
            - controller
          env:
            - name: CNPG_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            limits:
              memory: 512Mi
              cpu: "0.5"
            requests:
              memory: 256Mi
              cpu: "0.1"