apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.operator.fullnameOverride }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.operator.fullnameOverride }}
    app.kubernetes.io/component: operator
