apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"  # Deploy after CNPG operator and Keycloak
spec:
  project: default
  source:
    repoURL: https://github.com/yourusername/cloud-native-gauntlet.git
    targetRevision: HEAD
    path: charts/gitea
  destination:
    server: https://kubernetes.default.svc
    namespace: gitea
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
