apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30"  # Deploy after Keycloak and Gitea
spec:
  project: default
  source:
    repoURL: https://github.com/yourusername/cloud-native-gauntlet.git
    targetRevision: HEAD
    path: charts/todo-app
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
