---
- name: Install Docker from Ubuntu repositories
  apt:
    name:
      - docker.io
      - docker-compose
      - containerd
    state: present
    update_cache: yes
  retries: 3
  delay: 10

- name: Add vagrant user to docker group
  user:
    name: vagrant
    groups: docker
    append: yes

- name: Enable and start Docker service
  systemd:
    name: docker
    state: started
    enabled: yes
    daemon_reload: yes

- name: Configure Docker daemon
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "exec-opts": ["native.cgroupdriver=systemd"],
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "100m"
        },
        "storage-driver": "overlay2"
      }
  notify: restart docker

- name: Ensure Docker uses systemd cgroup driver
  lineinfile:
    path: /etc/docker/daemon.json
    regexp: '^\s*"exec-opts"'
    line: '  "exec-opts": ["native.cgroupdriver=systemd"],'
    insertafter: '^\{\s*$'
