---
- name: Configure common components on all nodes
  hosts: all
  become: true
  roles:
    - common
    - docker
    - registry
    - dns
  tags: [all]

- name: Configure K3s master node
  hosts: k3s_masters
  become: true
  roles:
    - k3s_control_plane
  tags: [master]

# Worker nodes are now configured as part of the master role on the same VM
