apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://gitea.local/nkwenti/infra.git
    targetRevision: HEAD
    path: . # This path needs to be updated once the infra repo structure is known
  destination:
    server: https://kubernetes.default.svc
    namespace: default # Or the namespace where Gitea and other infra components are deployed
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true